2019-04-29 09:20:13.351 -ERROR  [nio-9000-exec-1] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 09:20:13.351 -ERROR  [nio-9000-exec-1] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 09:20:14.773 -ERROR  [nio-9000-exec-1] o.a.j.l.DirectJDKLog           : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379] with root cause
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_144]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
2019-04-29 09:23:13.053 -ERROR  [nio-9000-exec-2] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 09:23:13.053 -ERROR  [nio-9000-exec-2] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 09:30:59.970 -ERROR  [nio-9000-exec-4] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 09:30:59.970 -ERROR  [nio-9000-exec-4] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 22:03:04.195 -ERROR  [nio-9000-exec-1] c.j.C.userController           : getExceptionLogger===日志测试
2019-04-29 22:03:04.195 -ERROR  [nio-9000-exec-1] c.j.C.userController           : getExceptionLogger===日志测试
